### ISSUE TITLE
wordembedding求解

### ISSUE THREAD

**Issue by lamaxiyasit** [yuelinan/NeurJudge#3]
跟您确认一下 代码里面默认每个单词的wordembedding都为1了吗

**Comment by yuelinan** [comment]
你好，当时这样设置是为了随机初始化word embedding矩阵。但是代码里好像没有实现这样的控制，可能是我从本地传到github上的时候，修改了代码造成了这个错误（我本地运行的时候使用的是embedding = toembedding()）。我已经重新修改了逻辑，并更新了train.py 和 model.py。

**Comment by lamaxiyasit** [comment]
好 我看你这个编码层用的gru并不是bert啊 可以提供下bert的版本吗 谢谢

**Comment by yuelinan** [comment]
可以的。我们实验室的服务器迁移过一次，代码我还得找下。可能在1月底sigir截稿之后我更新在GitHub上。

**Comment by yuelinan** [comment]
可以先关注一下这个项目：https://github.com/yuelinan/C3VG。数据和LJP任务一样都是裁判文书的数据。我用bart重新实现了一下，一些数据处理的代码和使用bert处理类似。

**Comment by lamaxiyasit** [comment]
好的 之前的话 通过toembedding获取到每个词的词向量。我发现使用了你提供的word2vec后 一些重要指标都得到的明显的提升了

**Comment by yuelinan** [comment]
是的。我记得我当时做实验的时候，使用预训练好的词向量 会比 使用随机的词向量 平均高2个点。

**Comment by lamaxiyasit** [comment]
论文里面的数据 使用的是随机的词向量还是预训练好的词向量得到啊

**Comment by yuelinan** [comment]
使用的预训练好的词向量

**Comment by lamaxiyasit** [comment]
好的 谢谢

**Comment by winnerLuo** [comment]
> 好 我看你这个编码层用的gru并不是bert啊 可以提供下bert的版本吗 谢谢

你好请问你有bert版本的吗
