### ISSUE TITLE
代码问题

### ISSUE THREAD

**Issue by lamaxiyasit** [yuelinan/NeurJudge#4]
model.py文件的138行是不是有问题，罪名和法条不应该用同一个编码器吧，但是我发现137行和138行使用同一个编码器了
<img width="1200" alt="image" src="https://github.com/yuelinan/NeurJudge/assets/52231452/756ded8e-81bc-46e4-b67d-e3634cc654e6">

**Comment by lamaxiyasit** [comment]
<img width="1200" alt="image" src="https://github.com/yuelinan/NeurJudge/assets/52231452/d0e9a011-df30-4b5a-ba38-950e58177710">

**Comment by yuelinan** [comment]
是使用的同一个编码器，主要是让罪名和法条共享一个编码器来节约显存。根据我的经验，使用不一样的编码器效果应该差不多。

**Comment by lamaxiyasit** [comment]
好的
