### ISSUE TITLE
请问下  这个数据集是基于CAIL2018数据集处理的吗

### ISSUE THREAD

**Issue by hecongqing** [yuelinan/NeurJudge#5]
CAIL2018数据集：https://cail.oss-cn-qingdao.aliyuncs.com/CAIL2018_ALL_DATA.zip

**Comment by yuelinan** [comment]
请问这个数据集是我上传的吗？我似乎没在这个网站上传过数据集

**Comment by hecongqing** [comment]
不是 ，想请问下 neurjudge的数据集 是基于什么数据集处理得到的

**Comment by yuelinan** [comment]
哦哦，是基于CAIL2018数据集处理的

**Comment by hecongqing** [comment]
这个数据集吗https://github.com/thunlp/CAIL
![image](https://github.com/yuelinan/NeurJudge/assets/19923817/f16f01b7-2a0c-4999-a8af-f3d684f8aa92)

**Comment by yuelinan** [comment]
是的，如果我没记错的话，CAIL2018应该是分了两个阶段的比赛，根据阶段的不同处理了数据集。

**Comment by hecongqing** [comment]
了解 感谢大佬解答
